/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.RegisteredUser;

/**
 *
 * @author 15877
 */
public class MainAppView extends javax.swing.JPanel {

        RegisteredUser user;

        /**
         * Creates new form NewJPanel
         */
        public MainAppView(RegisteredUser u) {
                user = u;
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                BrowseButton = new javax.swing.JButton();
                CancelTicketButton = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 153, 204));
                setPreferredSize(new java.awt.Dimension(850, 480));

                jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Movie Ticket Purchasing App");

                BrowseButton.setBackground(new java.awt.Color(255, 204, 204));
                BrowseButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                BrowseButton.setText("Browse Movies");
                BrowseButton.setToolTipText("Browse the Movie Catalogue");
                BrowseButton.setBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                BrowseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                BrowseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                BrowseButton.setSelected(true);

                CancelTicketButton.setBackground(new java.awt.Color(255, 204, 204));
                CancelTicketButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                CancelTicketButton.setText("Cancel Ticket");
                CancelTicketButton.setToolTipText("Cancel A Ticket You Previously Purchased");
                CancelTicketButton.setBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                CancelTicketButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                CancelTicketButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                CancelTicketButton.setSelected(true);

                jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
                if (user != null)
                        jLabel2.setText("Logged in as: " + user.getEmail());
                else
                        jLabel2.setText("Logged in as: Guest");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18).addComponent(jLabel1).addGap(260, 260, 260))
                                .addGroup(layout.createSequentialGroup().addGap(310, 310, 310).addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(CancelTicketButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(111, 111, 111)
                                                .addComponent(BrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(CancelTicketButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(146, Short.MAX_VALUE)));
        }// </editor-fold>

        public void addCancelTicketListener(java.awt.event.ActionListener listener) {
                CancelTicketButton.addActionListener(listener);
        }

        public void addMoviesListener(java.awt.event.ActionListener listener) {
                BrowseButton.addActionListener(listener);
        }

        // Variables declaration - do not modify
        private javax.swing.JButton BrowseButton;
        private javax.swing.JButton CancelTicketButton;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        // End of variables declaration
}
